# Generated by Django 4.2.16 on 2024-09-25 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="income",
            old_name="source",
            new_name="reason",
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
    ]
