# Generated by Django 4.2.16 on 2024-09-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_alter_income_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="chat_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
