# Generated by Django 4.2.16 on 2024-09-26 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0004_alter_user_chat_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Debt",
            new_name="Owe",
        ),
    ]
